name: C++ CI with GTest

on:
  push:
    branches: [ "main", "Electrosfera" ]
  pull_request:
    branches: [ "main", "Electrosfera" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Clang and C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake build-essential

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/VAM_Sim/build -S ${{github.workspace}}/VAM_Sim -DCMAKE_BUILD_TYPE=Debug

    - name: Build project and tests
      run: cmake --build ${{github.workspace}}/VAM_Sim/build --config Debug -j $(nproc)

    - name: Run C++ tests
      working-directory: ${{github.workspace}}/VAM_Sim/build
      run: ctest --output-on-failure